name: Update Players

on:
  schedule:
    - cron:  '*/5 4 * * *'

jobs:
  update:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Update Players
      run: python -c 'from sleeper import updatePlayers; updatePlayers()'
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
